"""Generate version_info.txt from __version__ in main.py.

__version__ is the one source of truth for the app's version. version_info.txt
is checked into the repo so a plain `pyinstaller TestAssist.spec` still works
without this script having run, but build.ps1 (and the release workflow) call
it before PyInstaller so the two files cannot drift the way they did for
v1.1.0, which shipped a binary whose Windows file properties still said 1.0.0.
"""

from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent

TEMPLATE = """# Windows version resource for the built executable.
# Generated by generate_version_info.py from __version__ in main.py - do not
# edit by hand, it will be overwritten at the next build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'emil3663'),
        StringStruct('FileDescription', 'Test Assist - QA evidence capture and annotation'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'TestAssist'),
        StringStruct('LegalCopyright', 'MIT Licence'),
        StringStruct('OriginalFilename', 'TestAssist.exe'),
        StringStruct('ProductName', 'Test Assist'),
        StringStruct('ProductVersion', '{version}'),
      ]),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def read_main_version() -> str:
    text = (HERE / "main.py").read_text(encoding="utf-8")
    match = re.search(r'^__version__\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not match:
        raise RuntimeError("__version__ not found in main.py")
    return match.group(1)


def render(version: str) -> str:
    parts = version.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise ValueError(f"expected a MAJOR.MINOR.PATCH version, got {version!r}")
    tup = f"({parts[0]}, {parts[1]}, {parts[2]}, 0)"
    return TEMPLATE.format(tup=tup, version=version)


def main() -> None:
    version = read_main_version()
    (HERE / "version_info.txt").write_text(render(version), encoding="utf-8", newline="\n")
    print(f"version_info.txt written for {version}")


if __name__ == "__main__":
    main()
